//! Reference: MIDI spec table III

use num_enum::{IntoPrimitive, TryFromPrimitive};

#[derive(IntoPrimitive, TryFromPrimitive)]
#[repr(u8)]
pub enum ControlNumber {
    BankSelect,
    ModulationWheelOrLever,
    BreathController,
    Undefined3 = 3,
    FootController,
    PortamentoTime,
    DataEntryMSB,
    ChannelVolume,
    Balance,
    Undefined9 = 9,
    Pan,
    ExpressionController,
    EffectControl1,
    EffectControl2,
    Undefined14 = 14,
    Undefined15 = 15,
    GeneralPurposeController1,
    GeneralPurposeController2,
    GeneralPurposeController3,
    GeneralPurposeController4,
    Undefined20 = 20,
    Undefined21 = 21,
    Undefined22 = 22,
    Undefined23 = 23,
    Undefined24 = 24,
    Undefined25 = 25,
    Undefined26 = 26,
    Undefined27 = 27,
    Undefined28 = 28,
    Undefined29 = 29,
    Undefined30 = 30,
    Undefined31 = 31,

    BankSelectLSB,
    ModulationWheelOrLeverLSB,
    BreathControllerLSB,
    Undefined3LSB,
    FootControllerLSB,
    PortamentoTimeLSB,
    DataEntryLSB,
    ChannelVolumeLSB,
    BalanceLSB,
    Undefined9LSB,
    PanLSB,
    ExpressionControllerLSB,
    EffectControl1LSB,
    EffectControl2LSB,
    Undefined14LSB,
    Undefined15LSB,
    GeneralPurposeController1LSB,
    GeneralPurposeController2LSB,
    GeneralPurposeController3LSB,
    GeneralPurposeController4LSB,
    Undefined20LSB,
    Undefined21LSB,
    Undefined22LSB,
    Undefined23LSB,
    Undefined24LSB,
    Undefined25LSB,
    Undefined26LSB,
    Undefined27LSB,
    Undefined28LSB,
    Undefined29LSB,
    Undefined30LSB,
    Undefined31LSB,

    DamperPedalSustain = 64,
    PortamentoOnOff,
    Sostenuto,
    SoftPedal,
    LegatoFootswitch,
    Hold2,

    TODO,
    
}
